---
name: Bot-Babelfish
version: 0.02
author:
  - Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: Provides Babelfish translation services via an IRC bot
license: perl
requires:
  Bot::BasicBot: 0.5
  Carp: 0
  Encode: 0
  I18N::LangTags: 0
  Lingua::Translate: 0
  Test::More: 0
provides:
  Bot::Babelfish:
    file: lib/Bot/Babelfish.pm
    version: 0.02
generated_by: Module::Build version 0.2608
