# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bot-Babelfish
version:      0.03
version_from: lib/Bot/Babelfish.pm
installdirs:  site
requires:
    Bot::BasicBot:                 0.5
    Carp:                          0
    Encode:                        0
    I18N::LangTags:                0
    Lingua::Translate:             0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
