#!/usr/bin/perl
use strict;
use Bot::Babelfish;

Bot::Babelfish->new(
        nick => 'babel', 
        name => 'Babelfish bot', 
        server => 'irc.perl.org', 
        channels => ['#perlfr','#babel']
    )->run

